freebsd_instance:
  image_family: freebsd-13-2

freebsd_client_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.2
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && cd mirage-client && mirage configure -t hvt
  depend_script: eval `opam env` && cd mirage-client && gmake depend
  copy_script: rm -rf mirage-client/duniverse/miragevpn/* && cp -R dune-project miragevpn.opam src mirage mirage-client/duniverse/miragevpn/
  build_script: eval `opam env` && cd mirage-client && gmake build
  client_artifacts:
    path: mirage-client/dist/ovpn-client.hvt

freebsd_nat_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.2
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && cd mirage-nat && mirage configure -t hvt
  depend_script: eval `opam env` && cd mirage-nat && gmake depend
  copy_script: rm -rf mirage-nat/duniverse/miragevpn/* && cp -R dune-project miragevpn.opam src mirage mirage-nat/duniverse/miragevpn/
  build_script: eval `opam env` && cd mirage-nat && gmake build
  nat_artifacts:
    path: mirage-nat/dist/ovpn-nat.hvt

freebsd_router_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.2
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && cd mirage-router && mirage configure -t hvt --enable-monitoring
  depend_script: eval `opam env` && cd mirage-router && gmake depend
  copy_script: rm -rf mirage-router/duniverse/miragevpn/* && cp -R dune-project miragevpn.opam src mirage mirage-router/duniverse/miragevpn/
  build_script: eval `opam env` && cd mirage-router && gmake build
  router_artifacts:
    path: mirage-router/dist/ovpn-router.hvt

freebsd_server_task:
  pkg_install_script: pkg install -y ocaml-opam gmake bash
  ocaml_script: opam init -a --comp=4.14.2
  mirage_script: eval `opam env` && opam install --confirm-level=unsafe-yes "mirage>=4.5.0"
  configure_script: eval `opam env` && cd mirage-server && mirage configure -t hvt
  depend_script: eval `opam env` && cd mirage-server && gmake depend
  copy_script: rm -rf mirage-server/duniverse/miragevpn/* && cp -R dune-project miragevpn.opam src mirage mirage-server/duniverse/miragevpn/
  build_script: eval `opam env` && cd mirage-server && gmake build
  server_artifacts:
    path: mirage-server/dist/ovpn-server.hvt
